title: "P.A.W's Handcrafted Soaps"
description: "Handmade soaps with cozy rustic charm"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
header:
  nav:
    - title: "Home"
      url: /
    - title: "Shop"
      url: /shop/
    - title: "Checkout"
      url: /checkout/
    - title: "About"
      url: /about/
url: "https://pawssoaps.github.io"
baseurl: "/paws-soaps-web-stuff"

